In [3]:
hex(1024)

'0x400'

In [9]:
a=2
b=3.34
a+b

5.34

In [10]:
a-b

-1.3399999999999999

In [11]:
a*b

6.68

In [12]:
a**b

10.126052751762238

In [13]:
a**a

4

In [15]:
b**a

11.1556

In [16]:
a>b

False

In [21]:
b>a

True

SyntaxError: invalid syntax (<ipython-input-25-f996fd41ee8e>, line 1)

In [30]:
import numpy import linspace, sin, exp, pi
import matplotlib,pyplot as mp
x=linspace(0,10*pi,500)
y=sin(x) * exp(-x/10)
mp.plot(x,y)
mp.show()

SyntaxError: invalid syntax (<ipython-input-30-24fa69670628>, line 1)

In [31]:
import calendar;
c1=calendar.month(2021,10)

In [32]:
print(c1)

    October 2021
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



In [35]:
c1=calendar.month(2021,10,22)
print(c1)

                                                                          October 2021
        Monday                Tuesday               Wednesday               Thursday                Friday                Saturday                Sunday
                                                                                                       1                      2                      3
           4                      5                      6                      7                      8                      9                     10
          11                     12                     13                     14                     15                     16                     17
          18                     19                     20                     21                     22                     23                     24
          25                     26                     27                     28                     29                     30                     31



In [37]:
c1=calendar.month(2021,10,10)
print(c1)

                                October 2021
  Monday    Tuesday   Wednesday   Thursday    Friday    Saturday    Sunday
                                                 1          2          3
     4          5          6          7          8          9         10
    11         12         13         14         15         16         17
    18         19         20         21         22         23         24
    25         26         27         28         29         30         31



In [41]:
c1=calendar.month(2021,1,10)
print(c1)

                                January 2021
  Monday    Tuesday   Wednesday   Thursday    Friday    Saturday    Sunday
                                                 1          2          3
     4          5          6          7          8          9         10
    11         12         13         14         15         16         17
    18         19         20         21         22         23         24
    25         26         27         28         29         30         31



In [3]:
import time;

In [4]:
t1=time.localtime(time.time())
print(t1)

time.struct_time(tm_year=2021, tm_mon=11, tm_mday=4, tm_hour=19, tm_min=54, tm_sec=27, tm_wday=3, tm_yday=308, tm_isdst=0)


In [8]:
t=time.localtime(time.time())
print(t)

time.struct_time(tm_year=2021, tm_mon=11, tm_mday=4, tm_hour=19, tm_min=55, tm_sec=42, tm_wday=3, tm_yday=308, tm_isdst=0)


In [9]:
t1=time.asctime(time.localtime(time.time()))

In [10]:
print(t1)

Thu Nov  4 19:56:01 2021


In [12]:
import calendar;


In [15]:
c1=calendar.month(2021,10)

In [16]:
print(c1)

    October 2021
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



In [23]:
c2=calendar.prcal(2020,5)
c2=calendar.prcal(2021)

                                                                  2020

                 January                                        February                                        March
 Mon   Tue   Wed   Thu   Fri   Sat   Sun        Mon   Tue   Wed   Thu   Fri   Sat   Sun        Mon   Tue   Wed   Thu   Fri   Sat   Sun
               1     2     3     4     5                                        1     2                                              1
   6     7     8     9    10    11    12          3     4     5     6     7     8     9          2     3     4     5     6     7     8
  13    14    15    16    17    18    19         10    11    12    13    14    15    16          9    10    11    12    13    14    15
  20    21    22    23    24    25    26         17    18    19    20    21    22    23         16    17    18    19    20    21    22
  27    28    29    30    31                     24    25    26    27    28    29               23    24    25    26    27    28    29


In [25]:
import datetime
mylist = []
today = datetime.date.today()
mylist.append(today)
print(mylist)

[datetime.date(2021, 11, 4)]


In [26]:
t1=time.localtime(time.time())

In [27]:
print(t1)

time.struct_time(tm_year=2021, tm_mon=11, tm_mday=4, tm_hour=20, tm_min=6, tm_sec=49, tm_wday=3, tm_yday=308, tm_isdst=0)


In [34]:
t1=time.asctime(time.localtime(time.time()))
                

In [35]:
print(t1)

Thu Nov  4 20:10:20 2021


In [38]:
import time
import datetime
print("week number of the year: ",datetime.date.today().strftime("%w"))

week number of the year:  4


In [39]:
print("Day of the year: ",datetime.date.today().strftime("%j"))

Day of the year:  308


In [40]:
print("day of the month: ",datetime.date.today().strftime("%w"))

day of the month:  4


In [44]:
print("day of the week :" ",datetime.date.today().strftime("%A"))

SyntaxError: EOL while scanning string literal (<ipython-input-44-db2a28eb8635>, line 1)

# NUMPY ARRAY INDEXING 

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])
print(arr[1])

2


In [5]:
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [6]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print( '2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  2


In [7]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print( '5nd element on 1st row: ',arr[1,4])

5nd element on 1st row:  10


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [9]:
print(arr[4:])

[5 6 7]


In [10]:
print(arr[:4])

[1 2 3 4]


In [11]:
print(arr[-3:-2])

[5]


In [12]:
print(arr[1:5:2])

[2 4]


In [13]:
print(arr[::2])

[1 3 5 7]


In [14]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [15]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [16]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [17]:
arr=np.array([1,2,3,4,5,])
print(arr[0:5])

[1 2 3 4 5]


In [18]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [19]:
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [20]:
arra=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4]
[1 2 3 4]


In [21]:
arr[1]=22

In [22]:
print(arr)

[42 22  3  4]


In [23]:
arra=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42 22  3  4]
[42 22  3  4]


In [24]:
arra=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
arr[0]=42
print(x.base)
print(y.base)

None
[42 22  3  4]


In [25]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [26]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,3)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [29]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,4)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
arr=np.array([[1,2,3], [4,5,6,]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [32]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [33]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
          for z in y:
                     print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [34]:
arr=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
for x in arr:
    for y in x:
          for z in y:
                for a in z:
                     print(a)

1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
arr=np.array([[1,2,3,4],[5,6,7,8,]])
for x in arr:
     np.nditer(arr[:, ::2])
                 print(x)

IndentationError: unexpected indent (<ipython-input-35-9703116b7fab>, line 4)

In [36]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [37]:
arr1=np.array([[[1,2,3,4]]])
arr2=np.array([[[5,6,7,8]]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]]


In [38]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)


In [39]:
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [40]:
ashu=np.array([1,2,3,4,5,6])
newarr=np.array_split(ashu,3)

In [41]:
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [42]:
ashu=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,5)

In [55]:
print(newarr)

[array([[1, 4]]), array([[2, 5]]), array([[3, 6]])]


In [56]:
import numpy as np
ashu=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)


In [57]:
def multiply(x,y=0):
    print("value of x=",x)
    print("value of y=",y)
    return x*y
    print(multiply(y=2,x=4))

In [1]:
x=0
while(x<4):
    print(x)
    x=x+1

0
1
2
3


In [2]:
x=0
while(x<4):
    print(x)
    x=x+1

0
1
2
3


In [3]:
x=0
while(x<10):
    print(x)
    x=x+1


0
1
2
3
4
5
6
7
8
9


In [6]:
x=0
for x in range(2,8):
    print(x)
    x=x+1
    


2
3
4
5
6
7


In [10]:
for x in range(10,20):
    if(x==15): break
    print(x)

10
11
12
13
14


In [11]:
for x in range(10,20):
    if(x==15): continue
    print(x)

10
11
12
13
14
16
17
18
19


In [13]:
for x in range(10,20):
    if(x==15): break
    print(x)

10
11
12
13
14


In [17]:
months=["jan","feb","mar","April","May","june"]
for i, m in enumerate(months):
    print(i,m)

0 jan
1 feb
2 mar
3 April
4 May
5 june


In [19]:
year=[2001,2002,2003,2004]
for i, m in enumerate(year):
    print(i,m)

0 2001
1 2002
2 2003
3 2004


In [21]:
days=["sun","mon","tue","wed","thu","fri","sat"]
for i, m in enumerate(days):
    print(days)

['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']


In [28]:
for i in '1234':
    print("ashu", i)

ashu 1
ashu 2
ashu 3
ashu 4


In [34]:
for i in range(4):
    for j in range(4):
        if j==2:
            break
            print("The number is ",i,j);

In [48]:
for i in range(10):
    if i == 7:
        continue
        print("The Number is:",i)

In [51]:
print("The Number is:",i+1)

The Number is: 10


In [52]:
for i in range(10):
    if i == 7:
        continue
        print("The Number is:",i)